# Generated by Django 3.2 on 2022-03-19 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_alter_shiftgroup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftday',
            name='type',
            field=models.CharField(max_length=21, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=21)]),
        ),
    ]
