# Generated by Django 3.2 on 2022-01-09 17:30

import back.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobj',
            name='file',
            field=models.FileField(default='', upload_to=back.models.FileObj.change_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
        migrations.AlterField(
            model_name='fileobj',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
