# Generated by Django 3.2 on 2022-04-11 07:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0002_alter_shiftday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=9110, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='in_shift',
            field=models.BooleanField(default=True, verbose_name='حضور در شیفت'),
        ),
        migrations.AlterField(
            model_name='shiftgroup',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'تنها حروف البای انگلیسی مجاز است!')], verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='shiftgroup',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='shiftgroup',
            name='phone_number',
            field=models.IntegerField(default=9090, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='shiftgroup',
            name='pr_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فارسی'),
        ),
        migrations.AlterField(
            model_name='shiftgroup',
            name='prefix',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='نام اختصاری'),
        ),
    ]
