# Generated by Django 3.2 on 2022-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_remove_fileobj_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileobj',
            name='shift_number',
            field=models.IntegerField(default=9090, verbose_name='تلفن شیفت'),
        ),
    ]
