# Generated by Django 3.2 on 2022-04-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20220411_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftday',
            name='day_responsible_pr',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shiftday',
            name='night_responsible_pr',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
