# Generated by Django 3.2 on 2022-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_profile_shift_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftgroup',
            name='shift_count_limit',
            field=models.IntegerField(default=5, verbose_name='تعداد شیفت در ماه'),
        ),
    ]
