# Generated by Django 3.2 on 2022-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_shiftgroup_shift_count_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='friday',
            name='back_people_list',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='thursday',
            name='back_people_list',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='back_people_list',
            field=models.TextField(default=None),
        ),
    ]
