# Generated by Django 3.2 on 2022-01-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_fileobj_shift_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sample_name', max_length=30)),
                ('columns', models.TextField(default='sample column1|sample_column2|sample column3')),
            ],
        ),
    ]
