# Generated by Django 3.2 on 2022-01-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_excelcolumns'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileobj',
            name='related_column',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='back.excelcolumns'),
        ),
    ]
