# Generated by Django 3.2 on 2022-01-15 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0007_fileobj_related_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileobj',
            options={'permissions': (('can_update_file', 'can_update_file'), ('can_see_file', 'can_update_file'))},
        ),
        migrations.AlterField(
            model_name='shiftgroup',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
