# Generated by Django 3.2 on 2022-01-15 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_auto_20220115_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobj',
            name='related_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.excelcolumns'),
        ),
    ]
