# Generated by Django 3.2 on 2022-02-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='in_shift',
            field=models.BooleanField(default=True),
        ),
    ]
