# Generated by Django 3.2 on 2022-02-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_profile_in_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup'),
        ),
    ]
