# Generated by Django 3.2 on 2022-02-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftgroup',
            options={'permissions': (('can_see_management', 'can_see_management'), ('can_add_shift_on_page', 'can_add_shift_on_page'))},
        ),
    ]
