# Generated by Django 3.2 on 2022-02-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_auto_20220209_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_month_num', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('j_year_num', models.IntegerField(choices=[(1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407), (1408, 1408), (1409, 1409)], verbose_name='سال')),
                ('people_list', models.TextField()),
                ('days_count', models.IntegerField()),
                ('days_name', models.TextField()),
                ('days_type', models.TextField()),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_list', models.TextField(default=None)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_list', models.TextField(default=None)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ORD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MEH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_list', models.TextField(default=None)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ESF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DAY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BAH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AZA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ABA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30)),
                ('night_responsible', models.CharField(default=None, max_length=30)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
