# Generated by Django 3.2 on 2022-02-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_aba_aza_bah_day_esf_far_friday_kho_meh_mor_ord_sha_shift_thursday_tir_tuesday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup'),
        ),
    ]
