# Generated by Django 3.2 on 2022-02-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_alter_shiftgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftgroup',
            name='phone_number',
            field=models.IntegerField(default=9090, verbose_name='تعداد شیفت در ماه'),
        ),
    ]
