# Generated by Django 3.2 on 2022-02-09 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup'),
        ),
    ]
