# Generated by Django 3.2 on 2022-02-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_alter_shift_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='days_type',
        ),
    ]
