# Generated by Django 3.2 on 2022-03-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_auto_20220310_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='j_day_num_first',
            field=models.IntegerField(null=True, verbose_name='از روز'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='j_day_num_last',
            field=models.IntegerField(null=True, verbose_name='تا روز'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='j_month_num_first',
            field=models.IntegerField(choices=[('', 'انتخاب کنید...'), (1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], null=True, verbose_name='از ماه'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='j_month_num_last',
            field=models.IntegerField(choices=[('', 'انتخاب کنید...'), (1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], null=True, verbose_name='تا ماه'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='j_year_num_first',
            field=models.IntegerField(choices=[(1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407), (1408, 1408), (1409, 1409), ('', 'انتخاب کنید...')], null=True, verbose_name='از سال'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='j_year_num_last',
            field=models.IntegerField(choices=[(1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407), (1408, 1408), (1409, 1409), ('', 'انتخاب کنید...')], null=True, verbose_name='تا سال'),
        ),
    ]
