# Generated by Django 3.2 on 2022-03-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_auto_20220313_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftday',
            name='type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
