# Generated by Django 3.2 on 2022-03-13 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0024_alter_shiftday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftday',
            name='uniq_id',
            field=models.CharField(default=None, max_length=19),
        ),
        migrations.AlterField(
            model_name='shiftday',
            name='type',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='shiftgroup',
            name='prefix',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(limit_value=4)]),
        ),
    ]
