# Generated by Django 3.2 on 2022-03-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_auto_20220313_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftday',
            name='uniq_id',
            field=models.CharField(max_length=19),
        ),
    ]
