# Generated by Django 3.2 on 2022-03-13 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0027_auto_20220313_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftday',
            name='type',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=19)]),
        ),
    ]
