# Generated by Django 3.2 on 2022-02-16 11:23

import back.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sample_name', max_length=30)),
                ('columns', models.TextField(default='sample column1|sample_column2|sample column3')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_month_num', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('j_year_num', models.IntegerField(choices=[(1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407), (1408, 1408), (1409, 1409)], verbose_name='سال')),
                ('people_list', models.TextField()),
                ('days_count', models.IntegerField()),
                ('days_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftGroup',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('pr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(max_length=4)),
                ('tuesday_req', models.IntegerField(default=3, verbose_name='حداقل نفر سه\u200cشنبه')),
                ('thursday_req', models.IntegerField(default=2, verbose_name='حداقل نفر پنجشنبه')),
                ('friday_req', models.IntegerField(default=1, verbose_name='حداقل نفر جمعه')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_list', models.TextField(default=None)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_list', models.TextField(default=None)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_num', models.IntegerField(default=-1)),
                ('j_day_num', models.IntegerField(default=-1, verbose_name='روز')),
                ('j_month_num', models.IntegerField(verbose_name='ماه')),
                ('j_year_num', models.IntegerField(verbose_name='سال')),
                ('night_people_list', models.TextField()),
                ('day_people_list', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('day_responsible', models.CharField(default=None, max_length=30, null=True)),
                ('night_responsible', models.CharField(default=None, max_length=30, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.shift')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_shift', models.BooleanField(default=True)),
                ('in_night_shift', models.BooleanField(default=True)),
                ('in_day_shift', models.BooleanField(default=True)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_list', models.TextField(default=None)),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileObj',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], null=True, verbose_name='ماه')),
                ('year', models.IntegerField(blank=True, choices=[(1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407), (1408, 1408), (1409, 1409)], null=True, verbose_name='سال')),
                ('shift_number', models.IntegerField(verbose_name='تلفن شیفت')),
                ('file', models.FileField(default='', upload_to=back.models.FileObj.change_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])])),
                ('group_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.shiftgroup')),
                ('related_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.excelcolumns')),
            ],
            options={
                'permissions': (('can_update_file', 'can_update_file'), ('can_see_file', 'can_update_file')),
            },
        ),
    ]
