# Generated by Django 3.2 on 2022-02-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_shiftgroup_normal_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shift_count',
            field=models.IntegerField(default=0, verbose_name='تعداد شیفت'),
        ),
    ]
