# Generated by Django 3.2 on 2022-02-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20220217_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftday',
            name='day_pr_people_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shiftday',
            name='night_pr_people_list',
            field=models.TextField(),
        ),
    ]
