# Generated by Django 3.2 on 2022-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_auto_20220310_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='uncommon_holiday',
            new_name='uncommon_holiday_first',
        ),
        migrations.AddField(
            model_name='shift',
            name='uncommon_holiday_last',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftgroup',
            name='uncommon_holiday_req',
            field=models.IntegerField(default=1, verbose_name='حداقل نفر در تعطیلات رسمی'),
        ),
    ]
