# Generated by Django 3.2 on 2022-03-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_auto_20220310_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='uncommon_holiday_first',
            new_name='formally_holiday_first',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='uncommon_holiday_last',
            new_name='formally_holiday_last',
        ),
        migrations.RenameField(
            model_name='shiftgroup',
            old_name='uncommon_holiday_req',
            new_name='formally_holiday_req',
        ),
        migrations.AddField(
            model_name='shiftday',
            name='is_formally_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
