# Generated by Django 3.2 on 2022-03-13 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0026_alter_shiftday_uniq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftday',
            name='uniq_id',
        ),
        migrations.AlterField(
            model_name='shiftday',
            name='type',
            field=models.CharField(max_length=19, validators=[django.core.validators.MinLengthValidator(limit_value=19)]),
        ),
    ]
