# Generated by Django 3.2 on 2022-03-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0028_alter_shiftday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftgroup',
            name='rest_number',
            field=models.IntegerField(default=2, verbose_name='تعداد روز استخراحت'),
        ),
    ]
